/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_live_haiwang_livegiftsample_JNITest */

#ifndef _Included_com_live_haiwang_livegiftsample_JNITest
#define _Included_com_live_haiwang_livegiftsample_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_live_haiwang_livegiftsample_JNITest
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_live_haiwang_livegiftsample_JNITest_getStringFromC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
